<template>
  <svg
    width="40px"
    height="40px"
    viewBox="0 0 40 40"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <!-- Generator: Sketch 3.7.2 (28276) - http://www.bohemiancoding.com/sketch -->
    <defs></defs>
    <g
      id="SendGrid"
      stroke="none"
      stroke-width="1"
      fill="none"
      fill-rule="evenodd"
    >
      <g id="Tiara-Logo">
        <g id="tiara-logo" transform="translate(8.000000, 8.000000)">
          <rect
            id="99E1F4"
            fill="#99E1F4"
            x="8"
            y="16"
            width="8"
            height="8"
          ></rect>
          <rect
            id="99E1F4"
            fill="#99E1F4"
            x="0"
            y="8"
            width="8"
            height="8"
          ></rect>
          <rect
            id="009DD9"
            fill="#009DD9"
            x="8"
            y="8"
            width="8"
            height="8"
          ></rect>
          <rect
            id="00B3E3"
            fill="#00B3E3"
            x="16"
            y="8"
            width="8"
            height="8"
          ></rect>
          <rect
            id="00B3E3"
            fill="#00B3E3"
            x="8"
            y="0"
            width="8"
            height="8"
          ></rect>
          <rect
            id="1a82e2"
            fill="#1A82E2"
            x="0"
            y="16"
            width="8"
            height="8"
          ></rect>
          <rect
            id="1a82e2"
            fill="#1A82E2"
            x="16"
            y="0"
            width="8"
            height="8"
          ></rect>
        </g>
      </g>
    </g>
  </svg>
</template>
